AllCops:
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
  DisplayCopNames: true

BlockDelimiters:
  EnforcedStyle: semantic

Lint/AssignmentInCondition:
  Enabled: false

Metrics:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/IndentHash:
  Enabled: false

Style/CaseIndentation:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false
